[package]
name = "s3plot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0" }
anyhow = "1.0"
eframe = { version = "0.16.0", features = ["persistence"] }
epi = { version = "0.16.0", features = ["persistence"] }
rfd = "0.7.0"
