[package]
name = "s3plot"
version = "0.1.0"
edition = "2021"

[dependencies]
cods = { git = "https://github.com/saecki/comeondosomething" }
serde = { version = "1.0" }
anyhow = "1.0"
eframe = { version = "0.20.1", features = ["persistence", "dark-light"] }
egui = { version = "0.20.1", features = ["persistence"] }
egui_extras = "0.20.0"
rfd = "0.10.0"
