[package]
name = "s3plot"
version = "0.1.0"
edition = "2021"

[dependencies]
cods = { git = "https://github.com/saecki/comeondosomething" }
serde = { version = "1.0" }
anyhow = "1.0"
epi = { git = "https://github.com/emilk/egui", features = ["persistence"], rev = "6abdde0" }
eframe = { git = "https://github.com/emilk/egui", features = ["persistence"], rev = "6abdde0" }
egui = { git = "https://github.com/emilk/egui", features = ["persistence"], rev = "6abdde0" }
rfd = "0.8.0"
strum = { version = "0.23.0", features = ["strum_macros"] }
strum_macros = "0.23.1"
derive_more = "0.99"
