[package]
name = "s3plot"
version = "0.1.0"
edition = "2021"

[dependencies]
cods = { git = "https://github.com/saecki/comeondosomething" }
serde = { version = "1.0" }
anyhow = "1.0"
eframe = { path = "../egui/crates/eframe", features = ["persistence", "dark-light"] }
egui = { path = "../egui/crates/egui", features = ["persistence"] }
egui_extras = { path = "../egui/crates/egui_extras" }
rfd = "0.10.0"
strum = { version = "0.24.1", features = ["derive"] }
derive_more = "0.99"
