name: Build

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 0 1 * *' # monthly

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev
    - run: cargo build --release
    - run: cargo test --release
    - run: strip target/release/s3plot
    - uses: actions/upload-artifact@v2
      with:
        name: s3plot-linux
        path: target/release/s3plot
  
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - run: cargo build --release
    - run: cargo test --release
    - run: strip target/release/s3plot.exe
    - uses: actions/upload-artifact@v2
      with:
        name: s3plot-windows
        path: target/release/s3plot.exe
